/**
 * Types for the `virtual:partner-logos` module generated by the `partner-logos`
 * plugin in vite.config.ts, which scans client/public/Logos_Partners/.
 */
declare module "virtual:partner-logos" {
  export interface PartnerLogo {
    /** Root-relative URL under /public, already percent-encoded. */
    src: string;
    /** Organisation name derived from the filename — used as alt text. */
    name: string;
  }
  export const PARTNER_LOGOS: PartnerLogo[];
}
